name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-test:
    install:
      - pip install tox
    strategy:
      matrix:
        version: [py38, py312]
    script: tox -e ${{ matrix.version }} -n auto
